### PR TITLE
Binding for Message component

### PR DESCRIPTION
**Pull request by bojant987**
Hope everything is in order.
I'm fairly new to both Reason and OCaml.
Regards

### CODE REVIEW

**Comment by voodoos** [comment]
Hi Bojan, thanks for sharing your improvements !

Your code looks right to me, the only thing I noticed is that you named the `Message` sub-modules `MessageContent`, `MessageHeader` etc. But because these are sub-modules of `Message` you need to use `Message.MessageContent` to access them. It's less redundant do call them `Content`, `Header` etc and consistent with the rest of the library.

Furthermore :
```
[@bs.module "semantic-ui-react"] [@bs.scope "Message"] external react : ReasonReact.reactClass = "MessageContent";
```
Should be:
```
[@bs.module "semantic-ui-react"] [@bs.scope "Message"] external react : ReasonReact.reactClass = "Content";
```

I will test the component more thoroughly tomorrow or Monday and then merge the pull request.

**Comment by bojant987** [comment]
Yeah, that makes sense. I renamed them. 
Sorry for two commits, first one was accidental :)

**Comment by voodoos** [comment]
Done !

I will try to add some tests and CI to the repo soon to automate some of this process...

**Comment by bojant987** [comment]
Cool! Good luck!
Hopefully i'll find time to help with some of the tests.

**Pull request merged**
